env:
  TERM: xterm-256color
graphics:
  vsync: false
window:
  decorations: full
  dimensions:
    columns: 120
    lines: 50
  title: Alacritty
scrolling:
  history: 2000
font:
  normal:
    family: "JetBrainsMono Nerd Font Mono"
    style: Regular
  bold:
    family: "JetBrainsMono Nerd Font Mono"
    style: Bold
  italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: Italic
  bold_italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: Bold Italic
  size: 11
colors:
  primary:
    background: '0x303030'
    foreground: '0xc0caf5'
  normal:
    black: '0x1D202F'
    red: '0xf7768e'
    green: '0x9ece6a'
    yellow: '0xe0af68'
    blue: '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan: '0x7dcfff'
    white: '0xa9b1d6'
  bright:
    black: '0x414868'
    red: '0xf7768e'
    green: '0x9ece6a'
    yellow: '0xe0af68'
    blue: '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan: '0x7dcfff'
    white: '0xc0caf5'
selection:
  save_to_clipboard: true
mouse_bindings:
  - {mouse: Right, action: PasteSelection}
key_bindings:
  - {key: V, mods: Control, mode: ~Vi, action: Paste}
